spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 2
mybatis:
  configuration:
    map-underscore-to-camel-case: true #下划线转换为驼峰命名
logging:
  level:
    com:
      zzc:
        cache:
          mapper: debug
